### ISSUE TITLE
Default to `--help` without command

### ISSUE THREAD

**Issue by albfan** [frenkhub/xml-sorter#4]
By default xml-sorter expects a path.
```
node:internal/fs/utils:667
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (node:fs:575:10)
    at Object.readFileSync (node:fs:451:35)
    at Object.exports.readFileXML (/usr/lib/node_modules/xml-sorter/src/core.js:140:19)
    at Object.<anonymous> (/usr/lib/node_modules/xml-sorter/src/cli.js:35:18)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

Detect and just output the `--help`

**Comment by frenkhub** [comment]
Thank you for the feedback, now this issue is fixed!
